### ISSUE TITLE
Invalid token when parsing nested objects into JSON

### ISSUE THREAD

**Issue by segphault** [wilsonrmsorg/rethinkdb-multicorn-postgresql-fdw#2]
I'm testing this foreign data wrapper with my [Cats of Instagram](https://github.com/rethinkdb/cats-of-instagram) project. I use the following sql to create the foreign table:

```sql
create foreign table instacat (id varchar, images json, time timestamp) server rethink options (table_name 'instacat');
```

The value of the images property in the RethinkDB document is a nested object that looks sort of like this:

```json
"images": {
    "low_resolution": {"height": 306, "url": "...", "width": 306},
    "standard_resolution": {"height": 612, "url": "...", "width": 612},
    "thumbnail": {"height": 150, "url": "...", "width": 150}
}
```

When I perform a select (`select * from instacat`) I get the following error:

```
ERROR:  invalid input syntax for type json
DETAIL:  Token "=" is invalid.
CONTEXT:  JSON data, line 1: "low_resolution"=...
```

When I use the varchar type instead of json for the images property, I see text that looks like this:

```
"low_resolution"=>"url"=>”...", "width"=>306, "height"=>306, "thumbnail"=>"url"=>”…", "width"=>150, "height"=>150, "standard_resolution"=>"url"=>”...", "width"=>612, "height"=>612
```

Which is obviously not valid JSON. I think that the error I'm getting when using the JSON type occurs because it's trying to parse that content with the "=>" symbols. I'm not sure how it's getting transformed into that format, though.

**Comment by rotten** [comment]
I opened Issue #86 with the Multicorn folks for this.  It looks like I'll have to add a decorator that checks each column type and serializes the dictionary types with json.dumps() before returning them to Multicorn.  I should be able to get that in place this week.

**Comment by rotten** [comment]
I just merged some quick changes that should fix this issue.  Let me know if it still doesn't work right for you!
